[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
opt-level = 0
debug = true
incremental = true
split-debuginfo = "unpacked" # Improve link time on MSVC

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort" # We use tracing for errors, abort on panic for smaller binary and slightly better perf.
strip = true

